In [1]:
import numpy as np

In [2]:
import pandas as pd


In [76]:
df = pd.read_csv("sal.csv")

In [77]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [78]:
yoe = df.iloc[:,0:1]

In [79]:
yoe.values

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [80]:
sal = df.iloc[:,1:2]

In [81]:
sal.values

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 93940.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [86]:
!pip install scikit-learn

   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.0 MB 11.2 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.0 MB 11.9 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 10.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from sklearn.model_selection import train_test_split

In [90]:
x_train, x_test, y_train, y_test = train_test_split(yoe, sal, test_size=0.3)

In [91]:
from sklearn.linear_model import LinearRegression

In [92]:
lm = LinearRegression()

lm

In [93]:
lm.fit(x_train,y_train)

LinearRegression()

In [94]:
lm.coef_


array([[9678.23209705]])

In [95]:
y_pred = lm.predict(x_test)


In [96]:
y_pred

array([[ 63462.36959578],
       [ 69269.30885401],
       [ 45073.72861139],
       [118628.29254895],
       [112821.35329072],
       [117660.46933925],
       [ 64430.19280548],
       [127338.70143629],
       [ 94432.71230633]])

In [111]:
y_test.values

array([[ 63218.],
       [ 61111.],
       [ 43525.],
       [112635.],
       [105582.],
       [116969.],
       [ 55794.],
       [121872.],
       [ 98273.]])

In [112]:
err = y_pred-y_test.values

In [113]:
err

array([[  244.36959578],
       [ 8158.30885401],
       [ 1548.72861139],
       [ 5993.29254895],
       [ 7239.35329072],
       [  691.46933925],
       [ 8636.19280548],
       [ 5466.70143629],
       [-3840.28769367]])

In [114]:
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rms = mse**0.5

In [115]:
r2,mse,rms

(0.9622647404606431, 30782073.555334967, 5548.159474576679)

In [148]:
lm.predict([[-2.656999999]])


E:\Python3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[2.20174512]])